name: automerge

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@7854d3bd607dccdaf0b2c134b699a812c8960213"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
          BASE_BRANCHES: "main"
          # PULL_REQUEST: "4"

      - name: Merge pull requests (automerge-action)
        run: echo "Automerge action completed successfully"
