name: Automerge dev to main

on:
  push:
    branches:
      - dev

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes into main
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff origin/dev -m "Automatically merge changes from dev into main"
          git push origin main
