name: automerge
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.16.2
      - name: Merge pull requests (automerge-action)
        run: echo "Automerge action completed successfully"
env:
          GITHUB_TOKEN: "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"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
          PULL_REQUEST: "1234"
