name: Automerge dev to main

on:
  pull_request:
    branches:
      - dev

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "whoami-anoint"
          git config --global user.email "abhishekkfl@gmail.com"

      - name: Merge into main
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Automatically merged PR #${{ github.event.pull_request.number }} from dev"
          git push origin main
