name: automerge
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: pascalgn/automerge-action@v0.16.2
    - name: Merge pull requests (automerge-action)
      
