name: Automerge to Main

on:
  push:
    branches:
      - dev

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge dev --no-edit || (echo "Merge conflict occurred"; exit 1)
          # Exit 1 if merge has conflicts
          git push origin main
